In [1]:
import torch
import torch.nn as nn
import numpy as np
import scipy
import random

In [2]:
np2D = np.random.randint(0,10,[2,3])
np3D = np.random.randint(0,20,[2,3,4])
tensordot = torch.tensor([9])
tensor1D = torch.randint(0,10,[4])
tensor2D = torch.randint(0,20,[2,3])
tensor3D = torch.randint(0,20,[2,3,4])
mat2D = torch.randint(0,10,[4,4])
mat3D = torch.randint(0,20,[2,4,4])

In [3]:
# 根据mask挑选出element，返回1-D张量
mask = tensor2D.ge(6.)
masked_select1 = torch.masked_select(tensor2D, mask)
print(masked_select1)

tensor([ 8,  7,  6, 16, 18])


In [4]:
# gather
dim0idx = torch.argmax(tensor3D,dim=0)
print(tensor3D,'\n')
print(
    torch.gather( input=tensor3D, dim=0, index= dim0idx.view(1,*dim0idx.size()) )
)

tensor([[[ 2, 14, 18, 14],
         [ 7,  2, 12, 12],
         [18,  1,  3,  2]],

        [[13,  0, 15, 11],
         [19,  7,  8,  4],
         [ 2, 18,  1, 10]]]) 

tensor([[[13, 14, 18, 14],
         [19,  7, 12, 12],
         [18, 18,  3, 10]]])


In [5]:
# 增减axis
print( torch.unsqueeze(tensor3D,dim=0).size() )

torch.Size([1, 2, 3, 4])


In [6]:
# 交换axis
print( torch.transpose(tensor3D,0,2).size() )
print( torch.swapaxes(tensor3D,0,2).size() )
print()

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])



In [7]:
# 消除tensor的某个dimension
torch.unbind( tensor3D, dim=1 )

(tensor([[ 2, 14, 18, 14],
         [13,  0, 15, 11]]),
 tensor([[ 7,  2, 12, 12],
         [19,  7,  8,  4]]),
 tensor([[18,  1,  3,  2],
         [ 2, 18,  1, 10]]))

In [8]:
# tile重复堆积tensor
print( torch.tile(tensor3D, [2,1,3]).size() )

torch.Size([4, 3, 12])


In [9]:
# 在2个tensor之间选择
torch.where( tensor2D>6, tensor2D, -100)

tensor([[   8, -100,    7],
        [-100,   16,   18]])

数学操作，逐点式的

In [27]:
print(tensor2D,'\n')
print('指数')
print(torch.exp(tensor2D))
print('幂次')
print(torch.pow(tensor2D,2))
print('对数')
print(torch.log10(tensor2D))
print('逻辑运算')
print(torch.logical_not(tensor2D))
print('算数加法')
print(torch.add(tensor2D, torch.log(tensor2D)))
print('算数乘法')
print(torch.mul(tensor2D,3))
print('负数')
print(torch.negative(tensor2D))
print('平方square')
print(torch.square(tensor2D))
print('square root')
print(torch.sqrt(tensor2D))
print('逻辑斯蒂')
print(torch.sigmoid(tensor2D))
print('sign标志')
print(torch.sign(tensor2D))
print('截取整数')
print(torch.randn(2,5), '\n')
print(torch.trunc(torch.randn(2,5)))

tensor([[ 8,  5,  7],
        [ 6, 16, 18]]) 

指数
tensor([[2.9810e+03, 1.4841e+02, 1.0966e+03],
        [4.0343e+02, 8.8861e+06, 6.5660e+07]])
幂次
tensor([[ 64,  25,  49],
        [ 36, 256, 324]])
对数
tensor([[0.9031, 0.6990, 0.8451],
        [0.7782, 1.2041, 1.2553]])
逻辑运算
tensor([[False, False, False],
        [False, False, False]])
算数加法
tensor([[10.0794,  6.6094,  8.9459],
        [ 7.7918, 18.7726, 20.8904]])
算数乘法
tensor([[24, 15, 21],
        [18, 48, 54]])
负数
tensor([[ -8,  -5,  -7],
        [ -6, -16, -18]])
平方square
tensor([[ 64,  25,  49],
        [ 36, 256, 324]])
square root
tensor([[2.8284, 2.2361, 2.6458],
        [2.4495, 4.0000, 4.2426]])
逻辑斯蒂
tensor([[0.9997, 0.9933, 0.9991],
        [0.9975, 1.0000, 1.0000]])
sign标志
tensor([[1, 1, 1],
        [1, 1, 1]])
截取整数
tensor([[ 1.1237, -0.9470, -0.8959, -0.3733, -0.3131],
        [-0.2044, -0.5467,  1.5259, -1.1746, -0.4342]]) 

tensor([[1., 0., 1., -0., -0.],
        [0., -0., 0., -0., 0.]])


数学操作，约简式的

In [52]:
print(tensor2D,'\n')
print('极值')
print(torch.amax(tensor2D,0))
print(torch.max(tensor2D,0)[0])
print('极值索引')
print(torch.argmax(tensor2D,0))
print(torch.max(tensor2D,0).indices)
print('均值')
print(torch.mean(tensor2D.type(torch.float),1))
print('非nan均值')
print(torch.nanmean(tensor2D.to(torch.float),1))
print('标准差')
print(torch.std(tensor2D.type(torch.float),0))
print('和')
print(torch.sum(tensor2D,0))
print('非nan和')
print(torch.nansum(tensor2D,0))
print('积')
print(torch.prod(tensor2D,1))
print('唯一值')
print(torch.unique(tensor2D))
print('非零计数')
print(torch.count_nonzero(tensor2D))
print('布尔值统计')
print(torch.all(tensor2D,0))
print(torch.any(tensor2D,0))

tensor([[ 8,  5,  7],
        [ 6, 16, 18]]) 

极值
tensor([ 8, 16, 18])
tensor([ 8, 16, 18])
极值索引
tensor([0, 1, 1])
tensor([0, 1, 1])
均值
tensor([ 6.6667, 13.3333])
非nan均值
tensor([ 6.6667, 13.3333])
标准差
tensor([1.4142, 7.7782, 7.7782])
和
tensor([14, 21, 25])
非nan和
tensor([14, 21, 25])
积
tensor([ 280, 1728])
唯一值
tensor([ 5,  6,  7,  8, 16, 18])
非零计数
tensor(6)
布尔值统计
tensor([True, True, True])
tensor([True, True, True])


数学操作，比较