In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import scipy

In [2]:
np2D = np.random.randint(0,10,[2,3])
np3D = np.random.randint(0,20,[2,3,4])
tensordot = torch.tensor([9])
tensor1D = torch.randint(0,10,[4])
tensor2D = torch.randint(0,20,[2,3])
tensor3D = torch.randint(0,20,[2,3,4])
mat2D = torch.randint(0,10,[4,4])
mat3D = torch.randint(0,20,[2,4,4])

In [3]:
is_tensor = torch.is_tensor(tensor2D)
print(f'是不是张量：{is_tensor}')

是不是张量：True


In [4]:
nonzero = torch.is_nonzero(tensordot)
print(f'非零吗：{nonzero}')

非零吗：True


In [5]:
numel = torch.numel(tensor3D)
print(f'元素数量：{numel}')

元素数量：24


In [6]:
tensor1 = torch.tensor(np2D, dtype=float)
tensor2 = torch.tensor([[2,3],[6,7]], dtype=torch.int32)
print(f'创建张量:\n{tensor1}\n{tensor2}')

创建张量:
tensor([[1., 1., 7.],
        [1., 5., 2.]], dtype=torch.float64)
tensor([[2, 3],
        [6, 7]], dtype=torch.int32)


In [7]:
# asarray 略
torch.asarray([8,10])

tensor([ 8, 10])

In [8]:
# as_tensor创建tensor
as_tensor1 = torch.as_tensor(np2D)
as_tensor2 = torch.as_tensor(tensor2D)
print(f'查看id是否相同：\n{id(np2D)}  {id(as_tensor1)}\n{id(tensor2D)}  {id(as_tensor2)}')

查看id是否相同：
2496467875088  2496467991344
2496467991504  2496467991504


In [9]:
from_numpy1 = torch.from_numpy(np2D)
print(from_numpy1)

tensor([[1, 1, 7],
        [1, 5, 2]], dtype=torch.int32)


In [10]:
arange1 = torch.arange(0,10,step=2)
linspace1 = torch.linspace(1,8,steps=8)
logspace1 = torch.logspace(1,8,steps=8)
print(arange1,'\n',linspace1,'\n',logspace1)

tensor([0, 2, 4, 6, 8]) 
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]) 
 tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05, 1.0000e+06,
        1.0000e+07, 1.0000e+08])


In [11]:
full1 = torch.full([2,3], 3.1415926, dtype=torch.float64)
full2 = torch.full_like(tensor2D, 3.14159)
print(full1,'\n',full2)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]], dtype=torch.float64) 
 tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


In [12]:
# 返回每个非0 element的索引
argwhere1 = torch.argwhere(tensor3D)
print(argwhere1.dim(),'\n',argwhere1.size())
print( torch.nonzero(tensor3D).size() )

2 
 torch.Size([22, 3])
torch.Size([22, 3])


In [13]:
# stack拼接的4类/共6个函数
print(tensor3D.size())
print(f'{"":>10}stack函数，添加额外的axis')
print(torch.stack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D],dim=2).size())
print(f'{"":>10}第1个axis上cat，vstack、row_stack')
print(torch.vstack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D]).size())
print(torch.row_stack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D]).size())
print(f'{"":>10}第2个axis上cat，hstack、column_stack')
print(torch.hstack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D]).size())
print(torch.column_stack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D]).size())
print(f'{"":>10}第3个axis上cat，dstack')
print(torch.dstack([tensor3D,tensor3D,tensor3D,tensor3D,tensor3D]).size())

torch.Size([2, 3, 4])
          stack函数，添加额外的axis
torch.Size([2, 3, 5, 4])
          第1个axis上cat，vstack、row_stack
torch.Size([10, 3, 4])
torch.Size([10, 3, 4])
          第2个axis上cat，hstack、column_stack
torch.Size([2, 15, 4])
torch.Size([2, 15, 4])
          第3个axis上cat，dstack
torch.Size([2, 3, 20])


In [14]:
# split切分数据
print(tensor3D.size())
print(
    torch.tensor_split(tensor3D,[1,3],dim=2)[1].size()
)
print(
    torch.hsplit(tensor3D,[1,3])[1].size()
)
print(
    torch.split(tensor3D,[1,2,1],dim=2)[1].size()
)

torch.Size([2, 3, 4])
torch.Size([2, 3, 2])
torch.Size([2, 2, 4])
torch.Size([2, 3, 2])


In [15]:
# 分块，number of chunks
torch.chunk(tensor3D, 3, dim=-1)

(tensor([[[ 3.,  8.],
          [19.,  5.],
          [ 5.,  4.]],
 
         [[19., 17.],
          [ 5.,  0.],
          [11., 12.]]]),
 tensor([[[ 1., 11.],
          [ 3.,  0.],
          [ 9., 11.]],
 
         [[ 2., 13.],
          [10., 18.],
          [17.,  4.]]]))

In [16]:
# movedim和permute，都是view视图
print( torch.movedim(tensor3D,[2,0],[0,2]).size() )

torch.Size([4, 3, 2])


In [17]:
print( torch.narrow(tensor3D,2,1,3).size() )

torch.Size([2, 3, 3])


In [18]:
# gather
dim0idx = torch.argmax(tensor3D,dim=0,keepdim=True)
print(tensor3D,'\n\ngather一下:\n')
print( torch.gather(tensor3D,0,dim0idx) )

tensor([[[ 3.,  8.,  1., 11.],
         [19.,  5.,  3.,  0.],
         [ 5.,  4.,  9., 11.]],

        [[19., 17.,  2., 13.],
         [ 5.,  0., 10., 18.],
         [11., 12., 17.,  4.]]]) 

gather一下:

tensor([[[19., 17.,  2., 13.],
         [19.,  5., 10., 18.],
         [11., 12., 17., 11.]]])


数学操作，比较

In [19]:
print(tensor2D,'\n')
print('排序值')
print(torch.sort(tensor2D,dim=1).values)
print('排序索引')
print(torch.argsort(tensor2D,dim=1))
print('排序索引')
print(torch.sort(tensor2D,1)[1])
print('topk')
print(torch.topk(tensor2D,k=2,dim=1)[0],'\n',torch.topk(tensor2D,k=2,dim=1).indices)
print('大小比较')
print(torch.gt(tensor2D,6))

tensor([[3., 7., 8.],
        [3., 4., 3.]]) 

排序值
tensor([[3., 7., 8.],
        [3., 3., 4.]])
排序索引
tensor([[0, 1, 2],
        [0, 2, 1]])
排序索引
tensor([[0, 1, 2],
        [0, 2, 1]])
topk
tensor([[8., 7.],
        [4., 3.]]) 
 tensor([[2, 1],
        [1, 0]])
大小比较
tensor([[False,  True,  True],
        [False, False, False]])


In [20]:
mat4D = torch.randint(0,30,[2,3,4,4,])

In [21]:
print(mat4D)
print(torch.diagonal(mat4D,0,1,2))

tensor([[[[ 7, 14,  0, 17],
          [10,  3, 18, 12],
          [ 5, 19, 25, 16],
          [18, 15, 27,  7]],

         [[ 0, 17,  7,  5],
          [17,  0, 22, 24],
          [26, 28,  7, 28],
          [ 9,  8, 12,  3]],

         [[ 5,  2, 18, 24],
          [ 4, 10, 16, 21],
          [ 9, 14,  9, 11],
          [24, 20,  9, 27]]],


        [[[ 0, 25,  2,  1],
          [26, 16,  8, 22],
          [ 0, 19, 24,  8],
          [21, 26, 20, 26]],

         [[ 5, 19,  7,  4],
          [22,  6, 24,  1],
          [18, 11, 19, 29],
          [ 7, 20, 26, 21]],

         [[11, 19, 10, 29],
          [20, 26,  7, 17],
          [ 4, 17, 20, 17],
          [11,  9, 13, 17]]]])
tensor([[[ 7, 17,  9],
         [14,  0, 14],
         [ 0, 22,  9],
         [17, 24, 11]],

        [[ 0, 22,  4],
         [25,  6, 17],
         [ 2, 24, 20],
         [ 1,  1, 17]]])


In [22]:
print(tensor2D)
print(torch.roll(tensor2D,[1,2],[0,1]))

tensor([[3., 7., 8.],
        [3., 4., 3.]])
tensor([[4., 3., 3.],
        [7., 8., 3.]])
